---
# reference: https://docs.openstack.org/kolla-ansible/2024.1/user/quickstart.html
- name: Prepare VM to use Kolla Ansible
  vars:
    venv_path: /home/vagrant/app
  tasks:
    - name: Install various packages with dnf
      ansible.builtin.dnf:
        name:
          - git
          - python3-devel
          - libffi-devel
          - gcc
          - openssl-devel
          - python3-libselinux
        state: present
    - name: Create a Python virtual environment
      ansible.builtin.command:
        cmd: "python3 -m venv {{ venv_path }}"
    - name: Create the /etc/kolla directory
      ansible.builtin.file:
        path: "{{ venv_path }}/bin/activate"
        state: file
        mode: '0777'
    - name: Install Ansible
      ansible.builtin.pip:
        name: 'ansible-core>=2.15,<2.16.99'
        chdir: "{{ venv_path }}"
        virtualenv: "{{ venv_path }}"
    - name: Install Kolla Ansible
      ansible.builtin.pip:
        name: git+https://opendev.org/openstack/kolla-ansible@stable/2024.1    
        chdir: "{{ venv_path }}"
        virtualenv: "{{ venv_path }}"
    - name: Create the /etc/kolla directory
      ansible.builtin.file:
        path: /etc/kolla
        state: directory
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: '0777'
    - name: Copy Kolla configs
      ansible.builtin.shell:
        cmd: "cp -r {{ venv_path }}/share/kolla-ansible/etc_examples/kolla/* /etc/kolla"
    - name: Copy Kolla Inventory
      ansible.builtin.shell:
        cmd: "cp -r {{ venv_path }}/share/kolla-ansible/ansible/inventory/all-in-one ."
        chdir: "{{ venv_path }}"
    - name: Install Ansible deps
      ansible.builtin.shell: |
        source {{ venv_path }}/bin/activate
        kolla-ansible install-deps
      args:
        chdir: "{{ venv_path }}"
    

        
    

    

